# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.2
_src_path: https://github.com/jupyterlab/extension-template
author_email: konrad.jelen@gmail.com
author_name: Stellars Henson
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab_terminal_clipboard_extension
project_short_description: Jupyterlab extension to handle copy to clipboard actions
    in a terminal to allow copy to clipboard of the browser/user
python_name: jupyterlab_terminal_clipboard_extension
repository: ''
test: true

